/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/hero/hero.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './hero.component.css.shim';
import * as import11 from '@angular/common/src/directives/ng_for';
import * as import12 from '@angular/core/src/linker/template_ref';
import * as import13 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import14 from '../../../app/hero/hero-button.component';
import * as import15 from './hero-button.component.ngfactory';
var renderType_HeroComponent_Host:import0.RenderComponentType = (null as any);
class _View_HeroComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeroComponent_0_4:import3.HeroComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroComponent_Host0,renderType_HeroComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-hero',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeroComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeroComponent_0_4 = new import3.HeroComponent();
    this._appEl_0.initComponent(this._HeroComponent_0_4,[],compView_0);
    compView_0.create(this._HeroComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HeroComponent) && (0 === requestNodeIndex))) { return this._HeroComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeroComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeroComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HeroComponent_Host === (null as any))) { (renderType_HeroComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_HeroComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeroComponentNgFactory:import9.ComponentFactory<import3.HeroComponent> = new import9.ComponentFactory<import3.HeroComponent>('app-hero',viewFactory_HeroComponent_Host0,import3.HeroComponent);
const styles_HeroComponent:any[] = [import10.styles];
var renderType_HeroComponent:import0.RenderComponentType = (null as any);
class _View_HeroComponent0 extends import1.AppView<import3.HeroComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _appEl_14:import2.AppElement;
  _TemplateRef_14_5:any;
  _NgFor_14_6:import11.NgFor;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroComponent0,renderType_HeroComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','Hero');
    this.renderer.setElementAttribute(this._el_0,'id','hero');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','content');
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_4,'alt','');
    this.renderer.setElementAttribute(this._el_4,'class','logo');
    this.renderer.setElementAttribute(this._el_4,'src','../../assets/narcos.logo.png');
    this._text_5 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'h2',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Season 2 now available',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_9 = this.renderer.createElement(this._el_2,'p',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque id quam sapiente unde voluptatum alias vero debitis,\n			magnam quis quod.',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_12 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','button-wrapper');
    this._text_13 = this.renderer.createText(this._el_12,'\n			',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_12,(null as any));
    this._appEl_14 = new import2.AppElement(14,12,this,this._anchor_14);
    this._TemplateRef_14_5 = new import12.TemplateRef_(this._appEl_14,viewFactory_HeroComponent1);
    this._NgFor_14_6 = new import11.NgFor(this._appEl_14.vcRef,this._TemplateRef_14_5,this.parentInjector.get(import13.IterableDiffers),this.ref);
    this._text_15 = this.renderer.createText(this._el_12,'\n		',(null as any));
    this._text_16 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_18 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','overlay');
    this._text_19 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._anchor_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import11.NgFor) && (14 === requestNodeIndex))) { return this._NgFor_14_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.context.buttons;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_14_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_14_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_14_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_HeroComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HeroComponent> {
  if ((renderType_HeroComponent === (null as any))) { (renderType_HeroComponent = viewUtils.createRenderComponentType('/Users/raincal/ng2-daily-ui/003-landing-page/src/app/hero/hero.component.html',0,import8.ViewEncapsulation.Emulated,styles_HeroComponent,{})); }
  return new _View_HeroComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HeroComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _HeroButtonComponent_2_4:import14.HeroButtonComponent;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroComponent1,renderType_HeroComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'app-hero-button',(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import15.viewFactory_HeroButtonComponent0(this.viewUtils,this.injector(2),this._appEl_2);
    this._HeroButtonComponent_2_4 = new import14.HeroButtonComponent();
    this._appEl_2.initComponent(this._HeroButtonComponent_2_4,[],compView_2);
    compView_2.create(this._HeroButtonComponent_2_4,[],(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.HeroButtonComponent) && (2 === requestNodeIndex))) { return this._HeroButtonComponent_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._HeroButtonComponent_2_4.button = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeroButtonComponent_2_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeroComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeroComponent1(viewUtils,parentInjector,declarationEl);
}