/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/logo/logo.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './logo.component.css.shim';
var renderType_LogoComponent_Host:import0.RenderComponentType = (null as any);
class _View_LogoComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LogoComponent_0_4:import3.LogoComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LogoComponent_Host0,renderType_LogoComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-logo',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LogoComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LogoComponent_0_4 = new import3.LogoComponent();
    this._appEl_0.initComponent(this._LogoComponent_0_4,[],compView_0);
    compView_0.create(this._LogoComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LogoComponent) && (0 === requestNodeIndex))) { return this._LogoComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._LogoComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LogoComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LogoComponent_Host === (null as any))) { (renderType_LogoComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_LogoComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const LogoComponentNgFactory:import9.ComponentFactory<import3.LogoComponent> = new import9.ComponentFactory<import3.LogoComponent>('app-logo',viewFactory_LogoComponent_Host0,import3.LogoComponent);
const styles_LogoComponent:any[] = [import10.styles];
var renderType_LogoComponent:import0.RenderComponentType = (null as any);
class _View_LogoComponent0 extends import1.AppView<import3.LogoComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LogoComponent0,renderType_LogoComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','Logo');
    this.renderer.setElementAttribute(this._el_0,'id','logo');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,':svg:svg',(null as any));
    this.renderer.setElementAttribute(this._el_2,'height','81.386726');
    this.renderer.setElementAttribute(this._el_2,'id','svg3262');
    this.renderer.setElementAttribute(this._el_2,'version','1.1');
    this.renderer.setElementAttribute(this._el_2,'width','300');
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,':svg:g',(null as any));
    this.renderer.setElementAttribute(this._el_4,'id','layer1');
    this.renderer.setElementAttribute(this._el_4,'transform','translate(-384.28572,-428.81172)');
    this._text_5 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,':svg:g',(null as any));
    this.renderer.setElementAttribute(this._el_6,'id','g3235');
    this.renderer.setElementAttribute(this._el_6,'transform','matrix(2.5445375,0,0,2.5445375,1157.1714,-1457.8678)');
    this._text_7 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,':svg:path',(null as any));
    this.renderer.setElementAttribute(this._el_8,'d','m -203.09972,771.41415 c 1.6425,0.15875 3.2825,0.33 4.92,0.5075 l 3.615,-8.92625 3.43625,9.74875 c 1.76375,0.22125 3.525,0.4525 5.2825,0.695 l -6.02375,-17.09625 6.02625,-14.88 -5.10375,0 -0.0525,0.0725 -3.255,8.03875 -2.8575,-8.11125 -5.03875,0 5.2025,14.7625 -6.15125,15.18875 z');
    this.renderer.setElementAttribute(this._el_8,'id','path3015');
    this.renderer.setElementAttribute(this._el_8,'style','fill:\'#b81d24\'; fillOpacity: 1; fillRule:\'nonzero\'; stroke:\'none\';');
    this._text_9 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_10 = this.renderer.createElement(this._el_6,':svg:path',(null as any));
    this.renderer.setElementAttribute(this._el_10,'d','m -206.91147,771.06478 0,-29.60125 -5.0375,0 0,29.18625 c 1.68125,0.12875 3.36125,0.26875 5.0375,0.415');
    this.renderer.setElementAttribute(this._el_10,'id','path3019');
    this.renderer.setElementAttribute(this._el_10,'style','fill:\'#b81d24\'; fillOpacity: 1; fillRule:\'nonzero\'; stroke:\'none\';');
    this._text_11 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_12 = this.renderer.createElement(this._el_6,':svg:path',(null as any));
    this.renderer.setElementAttribute(this._el_12,'d','m -244.7486,769.4089 c 1.36,0 2.7175,0.01 4.07375,0.0213 l 0,-10.875 6.05125,0 0,-4.63125 -6.05125,0 0,-7.825 6.96875,0 0,-4.63625 -12.02625,0 0,27.95 c 0.3275,0 0.655,-0.004 0.98375,-0.004');
    this.renderer.setElementAttribute(this._el_12,'id','path3023');
    this.renderer.setElementAttribute(this._el_12,'style','fill:\'#b81d24\'; fillOpacity: 1; fillRule:\'nonzero\'; stroke:\'none\';');
    this._text_13 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_14 = this.renderer.createElement(this._el_6,':svg:path',(null as any));
    this.renderer.setElementAttribute(this._el_14,'d','m -260.3881,769.69191 c 1.6775,-0.06 3.3575,-0.11 5.04,-0.15125 l 0,-23.44125 4.7075,0 0,-4.63625 -14.45625,0 0,4.63625 4.70875,0 0,23.5925 z');
    this.renderer.setElementAttribute(this._el_14,'id','path3035');
    this.renderer.setElementAttribute(this._el_14,'style','fill:\'#b81d24\'; fillOpacity: 1; fillRule:\'nonzero\'; stroke:\'none\';');
    this._text_15 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_16 = this.renderer.createElement(this._el_6,':svg:path',(null as any));
    this.renderer.setElementAttribute(this._el_16,'d','m -298.91059,772.81378 0,-17.63625 5.96375,16.92375 c 1.83375,-0.20625 3.67125,-0.4 5.5125,-0.5825 l 0,-30.055 -4.8325,0 0,18.2675 -6.43625,-18.2675 -0.2075,0 -4.8325,0 0,31.98375 0.03,0 c 1.5975,-0.22125 3.19875,-0.43125 4.8025,-0.63375');
    this.renderer.setElementAttribute(this._el_16,'id','path3039');
    this.renderer.setElementAttribute(this._el_16,'style','fill:\'#b81d24\'; fillOpacity: 1; fillRule:\'nonzero\'; stroke:\'none\';');
    this._text_17 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_18 = this.renderer.createElement(this._el_6,':svg:path',(null as any));
    this.renderer.setElementAttribute(this._el_18,'d','m -269.95297,746.09903 0,-4.63625 -12.0275,0 0,24.9125 0,4.6375 0,0.004 c 3.99125,-0.345 7.99625,-0.63375 12.0175,-0.86875 l 0,-0.004 0,-1.33625 0,-3.3 c -2.325,0.135 -4.645,0.29125 -6.96,0.46375 l 0,-7.415 6.05125,0 0,-4.63375 -6.05125,0 0,-7.82375 6.97,0 z');
    this.renderer.setElementAttribute(this._el_18,'id','path3051');
    this.renderer.setElementAttribute(this._el_18,'style','fill:\'#b81d24\'; fillOpacity: 1; fillRule:\'nonzero\'; stroke:\'none\';');
    this._text_19 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_20 = this.renderer.createElement(this._el_6,':svg:path',(null as any));
    this.renderer.setElementAttribute(this._el_20,'d','m -223.72272,765.2864 0,-23.82375 -5.05875,0 0,23.605 0,4.63625 0,0.005 c 4.02375,0.1475 8.0325,0.35375 12.0275,0.6125 l 0,-0.006 0,-1.4975 0,-3.13875 c -2.31875,-0.15 -4.64125,-0.28 -6.96875,-0.3925');
    this.renderer.setElementAttribute(this._el_20,'id','path3055');
    this.renderer.setElementAttribute(this._el_20,'style','fill:\'#b81d24\'; fillOpacity: 1; fillRule:\'nonzero\'; stroke:\'none\';');
    this._text_21 = this.renderer.createText(this._el_6,'\n			',(null as any));
    this._text_22 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_24 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_25 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_LogoComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LogoComponent> {
  if ((renderType_LogoComponent === (null as any))) { (renderType_LogoComponent = viewUtils.createRenderComponentType('/Users/raincal/ng2-daily-ui/003-landing-page/src/app/logo/logo.component.html',0,import8.ViewEncapsulation.Emulated,styles_LogoComponent,{})); }
  return new _View_LogoComponent0(viewUtils,parentInjector,declarationEl);
}