/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.Logo[_ngcontent-%COMP%] {\n  width: 151px;\n  height: 41px;\n  margin-right: 10px;\n  -webkit-transition: margin .125s ease;\n  transition: margin .125s ease;\n}\n\n.Logo[_ngcontent-%COMP%]   svg[_ngcontent-%COMP%] {\n  -webkit-transform: scale(0.5);\n          transform: scale(0.5);\n  -webkit-transform-origin: 0 0;\n          transform-origin: 0 0;\n}\n.Logo[_ngcontent-%COMP%]   svg[_ngcontent-%COMP%]   path[_ngcontent-%COMP%] {\n  fill: #e50914;\n  -webkit-transition: fill .125s ease;\n  transition: fill .125s ease;\n}\n.Logo[_ngcontent-%COMP%]:hover {\n  cursor: pointer;\n  margin-top: 2px;\n}\n.Logo[_ngcontent-%COMP%]:hover   svg[_ngcontent-%COMP%]   path[_ngcontent-%COMP%] {\n  fill: #ffffff !important;\n}'];