/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/payment-form/payment-form.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './payment-form.component.css.shim';
import * as import11 from '@angular/forms/src/directives/ng_form';
import * as import12 from '@angular/forms/src/directives/ng_control_status';
import * as import13 from '@angular/common/src/directives/ng_for';
import * as import14 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import15 from '@angular/forms/src/directives/ng_model';
import * as import16 from '@angular/forms/src/directives/default_value_accessor';
import * as import17 from '@angular/forms/src/directives/number_value_accessor';
import * as import18 from '@angular/forms/src/directives/validators';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from '@angular/forms/src/directives/control_value_accessor';
import * as import23 from '@angular/forms/src/directives/ng_control';
import * as import24 from '@angular/forms/src/validators';
import * as import25 from '@angular/forms/src/directives/control_container';
import * as import26 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
var renderType_PaymentFormComponent_Host:import0.RenderComponentType = (null as any);
class _View_PaymentFormComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _PaymentFormComponent_0_4:import3.PaymentFormComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PaymentFormComponent_Host0,renderType_PaymentFormComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-payment-form',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PaymentFormComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PaymentFormComponent_0_4 = new import3.PaymentFormComponent();
    this._appEl_0.initComponent(this._PaymentFormComponent_0_4,[],compView_0);
    compView_0.create(this._PaymentFormComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.PaymentFormComponent) && (0 === requestNodeIndex))) { return this._PaymentFormComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._PaymentFormComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PaymentFormComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_PaymentFormComponent_Host === (null as any))) { (renderType_PaymentFormComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_PaymentFormComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const PaymentFormComponentNgFactory:import9.ComponentFactory<import3.PaymentFormComponent> = new import9.ComponentFactory<import3.PaymentFormComponent>('app-payment-form',viewFactory_PaymentFormComponent_Host0,import3.PaymentFormComponent);
const styles_PaymentFormComponent:any[] = [import10.styles];
var renderType_PaymentFormComponent:import0.RenderComponentType = (null as any);
class _View_PaymentFormComponent0 extends import1.AppView<import3.PaymentFormComponent> {
  _el_0:any;
  _NgForm_0_3:import11.NgForm;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import12.NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _TemplateRef_5_5:any;
  _NgFor_5_6:import13.NgFor;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _SelectControlValueAccessor_16_3:import14.SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_16_4:any[];
  _NgModel_16_5:import15.NgModel;
  _NgControl_16_6:any;
  _NgControlStatus_16_7:import12.NgControlStatus;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _TemplateRef_18_5:any;
  _NgFor_18_6:import13.NgFor;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _SelectControlValueAccessor_21_3:import14.SelectControlValueAccessor;
  _NG_VALUE_ACCESSOR_21_4:any[];
  _NgModel_21_5:import15.NgModel;
  _NgControl_21_6:any;
  _NgControlStatus_21_7:import12.NgControlStatus;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _TemplateRef_23_5:any;
  _NgFor_23_6:import13.NgFor;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _DefaultValueAccessor_33_3:import16.DefaultValueAccessor;
  _NumberValueAccessor_33_4:import17.NumberValueAccessor;
  _RequiredValidator_33_5:import18.RequiredValidator;
  _NG_VALIDATORS_33_6:any[];
  _NG_VALUE_ACCESSOR_33_7:any[];
  _NgModel_33_8:import15.NgModel;
  _NgControl_33_9:any;
  _NgControlStatus_33_10:import12.NgControlStatus;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PaymentFormComponent0,renderType_PaymentFormComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'form',(null as any));
    this._NgForm_0_3 = new import11.NgForm((null as any),(null as any));
    this._ControlContainer_0_4 = this._NgForm_0_3;
    this._NgControlStatusGroup_0_5 = new import12.NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','Title');
    this._text_3 = this.renderer.createText(this._el_2,'Payment information',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_5 = new import2.AppElement(5,0,this,this._anchor_5);
    this._TemplateRef_5_5 = new import19.TemplateRef_(this._appEl_5,viewFactory_PaymentFormComponent1);
    this._NgFor_5_6 = new import13.NgFor(this._appEl_5.vcRef,this._TemplateRef_5_5,this.parentInjector.get(import20.IterableDiffers),this.ref);
    this._text_6 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','ExpiryDate');
    this._text_8 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'div',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n			',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'label',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Expires on',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n			',(null as any));
    this._el_14 = this.renderer.createElement(this._el_9,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','Expiry');
    this._text_15 = this.renderer.createText(this._el_14,'\n				',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'select',(null as any));
    this.renderer.setElementAttribute(this._el_16,'name','month');
    this._SelectControlValueAccessor_16_3 = new import14.SelectControlValueAccessor(this.renderer,new import21.ElementRef(this._el_16));
    this._NG_VALUE_ACCESSOR_16_4 = [this._SelectControlValueAccessor_16_3];
    this._NgModel_16_5 = new import15.NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_16_4);
    this._NgControl_16_6 = this._NgModel_16_5;
    this._NgControlStatus_16_7 = new import12.NgControlStatus(this._NgControl_16_6);
    this._text_17 = this.renderer.createText(this._el_16,'\n          ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._appEl_18 = new import2.AppElement(18,16,this,this._anchor_18);
    this._TemplateRef_18_5 = new import19.TemplateRef_(this._appEl_18,viewFactory_PaymentFormComponent2);
    this._NgFor_18_6 = new import13.NgFor(this._appEl_18.vcRef,this._TemplateRef_18_5,this.parentInjector.get(import20.IterableDiffers),this.ref);
    this._text_19 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._text_20 = this.renderer.createText(this._el_14,'\n				',(null as any));
    this._el_21 = this.renderer.createElement(this._el_14,'select',(null as any));
    this.renderer.setElementAttribute(this._el_21,'name','year');
    this._SelectControlValueAccessor_21_3 = new import14.SelectControlValueAccessor(this.renderer,new import21.ElementRef(this._el_21));
    this._NG_VALUE_ACCESSOR_21_4 = [this._SelectControlValueAccessor_21_3];
    this._NgModel_21_5 = new import15.NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_21_4);
    this._NgControl_21_6 = this._NgModel_21_5;
    this._NgControlStatus_21_7 = new import12.NgControlStatus(this._NgControl_21_6);
    this._text_22 = this.renderer.createText(this._el_21,'\n          ',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_21,(null as any));
    this._appEl_23 = new import2.AppElement(23,21,this,this._anchor_23);
    this._TemplateRef_23_5 = new import19.TemplateRef_(this._appEl_23,viewFactory_PaymentFormComponent3);
    this._NgFor_23_6 = new import13.NgFor(this._appEl_23.vcRef,this._TemplateRef_23_5,this.parentInjector.get(import20.IterableDiffers),this.ref);
    this._text_24 = this.renderer.createText(this._el_21,'\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_14,'\n			',(null as any));
    this._text_26 = this.renderer.createText(this._el_9,'\n		',(null as any));
    this._text_27 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._el_28 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','CVCField');
    this._text_29 = this.renderer.createText(this._el_28,'\n			',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'label',(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'CVC',(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'\n			',(null as any));
    this._el_33 = this.renderer.createElement(this._el_28,'input',(null as any));
    this.renderer.setElementAttribute(this._el_33,'max','999');
    this.renderer.setElementAttribute(this._el_33,'name','number');
    this.renderer.setElementAttribute(this._el_33,'ngModel','');
    this.renderer.setElementAttribute(this._el_33,'placeholder','000');
    this.renderer.setElementAttribute(this._el_33,'required','');
    this.renderer.setElementAttribute(this._el_33,'type','number');
    this._DefaultValueAccessor_33_3 = new import16.DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_33));
    this._NumberValueAccessor_33_4 = new import17.NumberValueAccessor(this.renderer,new import21.ElementRef(this._el_33));
    this._RequiredValidator_33_5 = new import18.RequiredValidator();
    this._NG_VALIDATORS_33_6 = [this._RequiredValidator_33_5];
    this._NG_VALUE_ACCESSOR_33_7 = [
      this._DefaultValueAccessor_33_3,
      this._NumberValueAccessor_33_4
    ]
    ;
    this._NgModel_33_8 = new import15.NgModel(this._ControlContainer_0_4,this._NG_VALIDATORS_33_6,(null as any),this._NG_VALUE_ACCESSOR_33_7);
    this._NgControl_33_9 = this._NgModel_33_8;
    this._NgControlStatus_33_10 = new import12.NgControlStatus(this._NgControl_33_9);
    this._text_34 = this.renderer.createText(this._el_28,'\n		',(null as any));
    this._text_35 = this.renderer.createText(this._el_7,'\n	',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_37 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','CheckoutButton');
    this._text_38 = this.renderer.createText(this._el_37,'\n		',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'button',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'Book securely',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n		',(null as any));
    this._el_42 = this.renderer.createElement(this._el_37,'span',(null as any));
    this._el_43 = this.renderer.createElement(this._el_42,'i',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','fa fa-fw fa-lock');
    this._text_44 = this.renderer.createText(this._el_42,' Your credit card information is encrypted',(null as any));
    this._text_45 = this.renderer.createText(this._el_37,'\n	',(null as any));
    this._text_46 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_47 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'ngSubmit',this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'submit',this.eventHandler(this._handle_submit_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'reset',this.eventHandler(this._handle_reset_0_2.bind(this)));
    const subscription_0:any = this._NgForm_0_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_16,'ngModelChange',this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_16,'change',this.eventHandler(this._handle_change_16_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_16,'blur',this.eventHandler(this._handle_blur_16_2.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_16_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_21,'ngModelChange',this.eventHandler(this._handle_ngModelChange_21_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_21,'change',this.eventHandler(this._handle_change_21_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_21,'blur',this.eventHandler(this._handle_blur_21_2.bind(this)));
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_21_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_21_0.bind(this)));
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_33,'input',this.eventHandler(this._handle_input_33_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_33,'blur',this.eventHandler(this._handle_blur_33_1.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_33,'change',this.eventHandler(this._handle_change_33_2.bind(this)));
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import13.NgFor) && (5 === requestNodeIndex))) { return this._NgFor_5_6; }
    if (((token === import19.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import13.NgFor) && (18 === requestNodeIndex))) { return this._NgFor_18_6; }
    if (((token === import14.SelectControlValueAccessor) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._SelectControlValueAccessor_16_3; }
    if (((token === import22.NG_VALUE_ACCESSOR) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NG_VALUE_ACCESSOR_16_4; }
    if (((token === import15.NgModel) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgModel_16_5; }
    if (((token === import23.NgControl) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgControl_16_6; }
    if (((token === import12.NgControlStatus) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgControlStatus_16_7; }
    if (((token === import19.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import13.NgFor) && (23 === requestNodeIndex))) { return this._NgFor_23_6; }
    if (((token === import14.SelectControlValueAccessor) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._SelectControlValueAccessor_21_3; }
    if (((token === import22.NG_VALUE_ACCESSOR) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._NG_VALUE_ACCESSOR_21_4; }
    if (((token === import15.NgModel) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._NgModel_21_5; }
    if (((token === import23.NgControl) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._NgControl_21_6; }
    if (((token === import12.NgControlStatus) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._NgControlStatus_21_7; }
    if (((token === import16.DefaultValueAccessor) && (33 === requestNodeIndex))) { return this._DefaultValueAccessor_33_3; }
    if (((token === import17.NumberValueAccessor) && (33 === requestNodeIndex))) { return this._NumberValueAccessor_33_4; }
    if (((token === import18.RequiredValidator) && (33 === requestNodeIndex))) { return this._RequiredValidator_33_5; }
    if (((token === import24.NG_VALIDATORS) && (33 === requestNodeIndex))) { return this._NG_VALIDATORS_33_6; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (33 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_33_7; }
    if (((token === import15.NgModel) && (33 === requestNodeIndex))) { return this._NgModel_33_8; }
    if (((token === import23.NgControl) && (33 === requestNodeIndex))) { return this._NgControl_33_9; }
    if (((token === import12.NgControlStatus) && (33 === requestNodeIndex))) { return this._NgControlStatus_33_10; }
    if (((token === import11.NgForm) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgForm_0_3; }
    if (((token === import25.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._ControlContainer_0_4; }
    if (((token === import12.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgControlStatusGroup_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_9:any = this.context.models;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgFor_5_6.ngForOf = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._NgFor_5_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_5_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_14:any = 'month';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgModel_16_5.name = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.context.selectedMonth;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgModel_16_5.model = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    if ((changes !== (null as any))) { this._NgModel_16_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_22:any = this.context.months;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._NgFor_18_6.ngForOf = currVal_22;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_22,currVal_22);
      this._expr_22 = currVal_22;
    }
    if ((changes !== (null as any))) { this._NgFor_18_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_18_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_27:any = 'year';
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._NgModel_21_5.name = currVal_27;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_27,currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this.context.selectedYear;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._NgModel_21_5.model = currVal_28;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_28,currVal_28);
      this._expr_28 = currVal_28;
    }
    if ((changes !== (null as any))) { this._NgModel_21_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_35:any = this.context.years;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._NgFor_23_6.ngForOf = currVal_35;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_35,currVal_35);
      this._expr_35 = currVal_35;
    }
    if ((changes !== (null as any))) { this._NgFor_23_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_23_6.ngDoCheck(); }
    const currVal_41:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this._RequiredValidator_33_5.required = currVal_41;
      this._expr_41 = currVal_41;
    }
    changes = (null as any);
    const currVal_43:any = 'number';
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this._NgModel_33_8.name = currVal_43;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_43,currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this._NgModel_33_8.model = currVal_44;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_44,currVal_44);
      this._expr_44 = currVal_44;
    }
    if ((changes !== (null as any))) { this._NgModel_33_8.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_0_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_0,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_0_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_0_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_0_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_0,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_0_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_0_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_0,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_16:any = this._NgControlStatus_16_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_16,'ng-untouched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_16_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_16,'ng-touched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_16_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_16,'ng-pristine',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_16_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_16,'ng-dirty',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_16_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_16,'ng-valid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_16_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_16,'ng-invalid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_29:any = this._NgControlStatus_21_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_21,'ng-untouched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_21_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_21,'ng-touched',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_21_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_21,'ng-pristine',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_21_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_21,'ng-dirty',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_21_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_21,'ng-valid',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_21_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_21,'ng-invalid',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_42:any = (this._RequiredValidator_33_5.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementAttribute(this._el_33,'required',((currVal_42 == (null as any))? (null as any): currVal_42.toString()));
      this._expr_42 = currVal_42;
    }
    const currVal_45:any = this._NgControlStatus_33_10.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_33,'ng-untouched',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_33_10.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_33,'ng-touched',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._NgControlStatus_33_10.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_33,'ng-pristine',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_33_10.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_33,'ng-dirty',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this._NgControlStatus_33_10.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this.renderer.setElementClass(this._el_33,'ng-valid',currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = this._NgControlStatus_33_10.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_33,'ng-invalid',currVal_50);
      this._expr_50 = currVal_50;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_16_5.ngOnDestroy();
    this._NgModel_21_5.ngOnDestroy();
    this._NgModel_33_8.ngOnDestroy();
  }
  private _handle_ngSubmit_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit(this._NgForm_0_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_0_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_0_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.selectedMonth = $event)) !== false);
    const pd_1:any = ((<any>this.context.handleMonthChange($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_change_16_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SelectControlValueAccessor_16_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_16_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SelectControlValueAccessor_16_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.selectedYear = $event)) !== false);
    const pd_1:any = ((<any>this.context.handleYearChange($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_change_21_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SelectControlValueAccessor_21_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_21_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SelectControlValueAccessor_21_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_33_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_33_3.onChange($event.target.value)) !== false);
    const pd_1:any = ((<any>this._NumberValueAccessor_33_4.onChange($event.target.value)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_blur_33_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_33_3.onTouched()) !== false);
    const pd_1:any = ((<any>this._NumberValueAccessor_33_4.onTouched()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_change_33_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NumberValueAccessor_33_4.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_PaymentFormComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.PaymentFormComponent> {
  if ((renderType_PaymentFormComponent === (null as any))) { (renderType_PaymentFormComponent = viewUtils.createRenderComponentType('/Users/raincal/ng2-daily-ui/002-checkout/src/app/payment-form/payment-form.component.html',0,import8.ViewEncapsulation.Emulated,styles_PaymentFormComponent,{})); }
  return new _View_PaymentFormComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_PaymentFormComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _DefaultValueAccessor_5_3:import16.DefaultValueAccessor;
  _RequiredValidator_5_4:import18.RequiredValidator;
  _NG_VALIDATORS_5_5:any[];
  _NG_VALUE_ACCESSOR_5_6:any[];
  _NgModel_5_7:import15.NgModel;
  _NgControl_5_8:any;
  _NgControlStatus_5_9:import12.NgControlStatus;
  _text_6:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PaymentFormComponent1,renderType_PaymentFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','BasicInput');
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'label',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_5,'ngModel','');
    this.renderer.setElementAttribute(this._el_5,'required','');
    this._DefaultValueAccessor_5_3 = new import16.DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_5));
    this._RequiredValidator_5_4 = new import18.RequiredValidator();
    this._NG_VALIDATORS_5_5 = [this._RequiredValidator_5_4];
    this._NG_VALUE_ACCESSOR_5_6 = [this._DefaultValueAccessor_5_3];
    this._NgModel_5_7 = new import15.NgModel((<_View_PaymentFormComponent0>this.parent)._ControlContainer_0_4,this._NG_VALIDATORS_5_5,(null as any),this._NG_VALUE_ACCESSOR_5_6);
    this._NgControl_5_8 = this._NgModel_5_7;
    this._NgControlStatus_5_9 = new import12.NgControlStatus(this._NgControl_5_8);
    this._text_6 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'input',this.eventHandler(this._handle_input_5_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'blur',this.eventHandler(this._handle_blur_5_1.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.DefaultValueAccessor) && (5 === requestNodeIndex))) { return this._DefaultValueAccessor_5_3; }
    if (((token === import18.RequiredValidator) && (5 === requestNodeIndex))) { return this._RequiredValidator_5_4; }
    if (((token === import24.NG_VALIDATORS) && (5 === requestNodeIndex))) { return this._NG_VALIDATORS_5_5; }
    if (((token === import22.NG_VALUE_ACCESSOR) && (5 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_5_6; }
    if (((token === import15.NgModel) && (5 === requestNodeIndex))) { return this._NgModel_5_7; }
    if (((token === import23.NgControl) && (5 === requestNodeIndex))) { return this._NgControl_5_8; }
    if (((token === import12.NgControlStatus) && (5 === requestNodeIndex))) { return this._NgControlStatus_5_9; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_7:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RequiredValidator_5_4.required = currVal_7;
      this._expr_7 = currVal_7;
    }
    changes = (null as any);
    const currVal_9:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgModel_5_7.name = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgModel_5_7.model = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgModel_5_7.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'htmlFor',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.label,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_5,'id',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',this.context.$implicit.type,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_5,'type',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',this.context.$implicit.placeholder,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_5,'placeholder',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_8:any = (this._RequiredValidator_5_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementAttribute(this._el_5,'required',((currVal_8 == (null as any))? (null as any): currVal_8.toString()));
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._NgControlStatus_5_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_5,'ng-untouched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_5_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_5,'ng-touched',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatus_5_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_5,'ng-pristine',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_5_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_5,'ng-dirty',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_5_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_5,'ng-valid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_5_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_5,'ng-invalid',currVal_16);
      this._expr_16 = currVal_16;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_5_7.ngOnDestroy();
  }
  private _handle_input_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_5_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_5_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_5_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_PaymentFormComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PaymentFormComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_PaymentFormComponent2 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import14.NgSelectOption;
  _NgSelectMultipleOption_0_4:import26.NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PaymentFormComponent2,renderType_PaymentFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'option',(null as any));
    this._NgSelectOption_0_3 = new import14.NgSelectOption(new import21.ElementRef(this._el_0),this.renderer,(<_View_PaymentFormComponent0>this.parent)._SelectControlValueAccessor_16_3);
    this._NgSelectMultipleOption_0_4 = new import26.NgSelectMultipleOption(new import21.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3; }
    if (((token === import26.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
}
function viewFactory_PaymentFormComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PaymentFormComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_PaymentFormComponent3 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import14.NgSelectOption;
  _NgSelectMultipleOption_0_4:import26.NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_PaymentFormComponent3,renderType_PaymentFormComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'option',(null as any));
    this._NgSelectOption_0_3 = new import14.NgSelectOption(new import21.ElementRef(this._el_0),this.renderer,(<_View_PaymentFormComponent0>this.parent)._SelectControlValueAccessor_21_3);
    this._NgSelectMultipleOption_0_4 = new import26.NgSelectMultipleOption(new import21.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3; }
    if (((token === import26.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
}
function viewFactory_PaymentFormComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_PaymentFormComponent3(viewUtils,parentInjector,declarationEl);
}