/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.TitleList[_ngcontent-%COMP%] {\n  padding: 20px 40px;\n  box-sizing: border-box;\n  -webkit-transition: opacity 3s ease;\n  transition: opacity 3s ease;\n  opacity: 0;\n}\n\n.TitleList[data-loaded=\'true\'][_ngcontent-%COMP%] {\n  opacity: 1;\n}\n\n.List[_ngcontent-%COMP%]:nth-of-type(1) {\n  margin-top: -10vw;\n  position: relative;\n  z-index: 4;\n}'];