/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/user-profile/user-profile.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './user-profile.component.css.shim';
var renderType_UserProfileComponent_Host:import0.RenderComponentType = (null as any);
class _View_UserProfileComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UserProfileComponent_0_4:import3.UserProfileComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserProfileComponent_Host0,renderType_UserProfileComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-user-profile',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UserProfileComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserProfileComponent_0_4 = new import3.UserProfileComponent();
    this._appEl_0.initComponent(this._UserProfileComponent_0_4,[],compView_0);
    compView_0.create(this._UserProfileComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UserProfileComponent) && (0 === requestNodeIndex))) { return this._UserProfileComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._UserProfileComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserProfileComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UserProfileComponent_Host === (null as any))) { (renderType_UserProfileComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_UserProfileComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UserProfileComponentNgFactory:import9.ComponentFactory<import3.UserProfileComponent> = new import9.ComponentFactory<import3.UserProfileComponent>('app-user-profile',viewFactory_UserProfileComponent_Host0,import3.UserProfileComponent);
const styles_UserProfileComponent:any[] = [import10.styles];
var renderType_UserProfileComponent:import0.RenderComponentType = (null as any);
class _View_UserProfileComponent0 extends import1.AppView<import3.UserProfileComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserProfileComponent0,renderType_UserProfileComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','User');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','name');
    this._text_3 = this.renderer.createText(this._el_2,'Raincal',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','image');
    this._el_6 = this.renderer.createElement(this._el_5,'img',(null as any));
    this.renderer.setElementAttribute(this._el_6,'src','../assets/photo.png');
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_UserProfileComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.UserProfileComponent> {
  if ((renderType_UserProfileComponent === (null as any))) { (renderType_UserProfileComponent = viewUtils.createRenderComponentType('/Users/raincal/ng2-daily-ui/003-landing-page/src/app/user-profile/user-profile.component.html',0,import8.ViewEncapsulation.Emulated,styles_UserProfileComponent,{})); }
  return new _View_UserProfileComponent0(viewUtils,parentInjector,declarationEl);
}