/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/image-preview/image-preview.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './image-preview.component.css.shim';
import * as import11 from '../../../app/pluralize.pipe';
var renderType_ImagePreviewComponent_Host:import0.RenderComponentType = (null as any);
class _View_ImagePreviewComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ImagePreviewComponent_0_4:import3.ImagePreviewComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ImagePreviewComponent_Host0,renderType_ImagePreviewComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-image-preview',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ImagePreviewComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ImagePreviewComponent_0_4 = new import3.ImagePreviewComponent();
    this._appEl_0.initComponent(this._ImagePreviewComponent_0_4,[],compView_0);
    compView_0.create(this._ImagePreviewComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ImagePreviewComponent) && (0 === requestNodeIndex))) { return this._ImagePreviewComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ImagePreviewComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ImagePreviewComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ImagePreviewComponent_Host === (null as any))) { (renderType_ImagePreviewComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_ImagePreviewComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ImagePreviewComponentNgFactory:import9.ComponentFactory<import3.ImagePreviewComponent> = new import9.ComponentFactory<import3.ImagePreviewComponent>('app-image-preview',viewFactory_ImagePreviewComponent_Host0,import3.ImagePreviewComponent);
const styles_ImagePreviewComponent:any[] = [import10.styles];
var renderType_ImagePreviewComponent:import0.RenderComponentType = (null as any);
class _View_ImagePreviewComponent0 extends import1.AppView<import3.ImagePreviewComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  /*private*/ _expr_0:any;
  _arr_0:any;
  _pipe_pluralize_0:import11.PluralizePipe;
  _pipe_pluralize_0_0:any;
  /*private*/ _expr_1:any;
  _arr_1:any;
  _pipe_pluralize_0_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ImagePreviewComponent0,renderType_ImagePreviewComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'  ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','WorkspaceOverview');
    this._text_2 = this.renderer.createText(this._el_1,'\n\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','WorkspaceInformation');
    this._text_4 = this.renderer.createText(this._el_3,'\n      ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','WorkspaceName');
    this._text_6 = this.renderer.createText(this._el_5,'Coworking Space, South Korea',(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n      ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','WorkspacePrice');
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','Price');
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','Duration');
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._text_16 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_1,'\n\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','WorkspaceMeta');
    this._text_19 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','Description');
    this._text_21 = this.renderer.createText(this._el_20,'Entire office for ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'strong',(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_24 = this.renderer.createText(this._el_18,'\n      ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_18,'div',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','Dates');
    this._el_26 = this.renderer.createElement(this._el_25,'strong',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Mon, Aug 22, 2016',(null as any));
    this._text_28 = this.renderer.createText(this._el_25,' to ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_25,'strong',(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'Fri, Aug 29, 2016',(null as any));
    this._text_31 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_32 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._text_33 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._arr_0 = import4.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
    this._pipe_pluralize_0 = new import11.PluralizePipe();
    this._pipe_pluralize_0_0 = import4.pureProxy2(this._pipe_pluralize_0.transform.bind(this._pipe_pluralize_0));
    this._expr_1 = import7.UNINITIALIZED;
    this._arr_1 = import4.pureProxy2((p0:any,p1:any):any[] => {
      return [
        p0,
        p1
      ]
      ;
    });
    this._pipe_pluralize_0_1 = import4.pureProxy2(this._pipe_pluralize_0.transform.bind(this._pipe_pluralize_0));
    this._expr_2 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.state.price,' GBP');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_11,currVal_0);
      this._expr_0 = currVal_0;
    }
    valUnwrapper.reset();
    const currVal_1:any = import4.interpolate(1,'/ ',valUnwrapper.unwrap(import4.castByValue(this._pipe_pluralize_0_0,this._pipe_pluralize_0.transform)(this.context.duration,this._arr_0('day','days'))),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_1,currVal_1))) {
      this.renderer.setText(this._text_14,currVal_1);
      this._expr_1 = currVal_1;
    }
    valUnwrapper.reset();
    const currVal_2:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_pluralize_0_1,this._pipe_pluralize_0.transform)(this.context.state.people,this._arr_1('person','people'))),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_2,currVal_2))) {
      this.renderer.setText(this._text_23,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ImagePreviewComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ImagePreviewComponent> {
  if ((renderType_ImagePreviewComponent === (null as any))) { (renderType_ImagePreviewComponent = viewUtils.createRenderComponentType('/Users/raincal/ng2-daily-ui/002-checkout/src/app/image-preview/image-preview.component.html',0,import8.ViewEncapsulation.Emulated,styles_ImagePreviewComponent,{})); }
  return new _View_ImagePreviewComponent0(viewUtils,parentInjector,declarationEl);
}